import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SideNavbar from "@/components/SideNavBar";

import Image from "next/image";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn ('min-h-screen w-full bg-white text-black flex',inter.className, {'debug-screens' : process.env.NODE_ENV==='development'})}
      >
        {/* sidebar */}
        <div className="h-screen fixed sm:relative">
          <SideNavbar/>
        </div>
          
        {/* main page */}
        <div className="ml-[60px] sm:ml-0 p-4 md:px-8 w-full overflow-hidden ">{children}</div>
      </body>
    </html>
  );
}
